### ISSUE TITLE
don't work 

### ISSUE THREAD

**Issue by Hernou** [fossfreedom/rhythmbox_hide#3]
![GitHub Logo](http://i.imgur.com/J4plZGh.png)

http://i.imgur.com/J4plZGh.png

**Comment by fossfreedom** [comment]
Hi,

  please can you launch a terminal and then type

    rhythmbox

What is the output in the terminal when you activate the plugin?

**Comment by Hernou** [comment]
`
:~$ rhythmbox

(rhythmbox:25119): Gtk-CRITICAL **: gtk_css_provider_load_from_path: assertion 'path != NULL' failed

(rhythmbox:25119): Rhythmbox-WARNING **: Could not open device /dev/radio0

(rhythmbox:25119): libsoup-CRITICAL **: soup_server_quit: assertion 'priv->listeners != NULL' failed
sys:1: Warning: object SoupServer 0x2ed21c0 finalized while still in-construction
sys:1: Warning: Custom constructor for class SoupServer returned NULL (which is invalid). Please use GInitable instead.

(rhythmbox:25119): Gtk-WARNING **: Duplicate child name in GtkStack: Ajouter à la liste de lecture


(rhythmbox:25119): Gtk-WARNING **: Duplicate child name in GtkStack: Ajouter à la liste de lecture


(rhythmbox:25119): Gtk-WARNING **: Duplicate child name in GtkStack: Ajouter à la liste de lecture


(rhythmbox:25119): Gtk-WARNING **: Duplicate child name in GtkStack: Ajouter à la liste de lecture


(rhythmbox:25119): Gtk-WARNING **: Duplicate child name in GtkStack: Ajouter à la liste de lecture


(rhythmbox:25119): Gtk-WARNING **: Duplicate child name in GtkStack: Ajouter à la liste de lecture


(rhythmbox:25119): libpeas-WARNING **: The 'python' plugin loader has not been enabled

`

**Comment by fossfreedom** [comment]
Please look at the readme - follow the install command for your version of rhythmbox.  Thanks.

**Comment by Hernou** [comment]
:sweat_smile: 
Ok sorry, it work now, thanks you :smirk:

**Comment by llvasconcellos** [comment]
I have the same problem with a different plugin. Why this happens? I'm using Rhythmbox 3.2.1.
The plugin is too old? 
How can I solve the message: "The 'python' plugin loader has not been enabled"?

**Comment by fossfreedom** [comment]
@llvasconcellos 

  you have the "same problem with a different plugin"? What plugin?

**Comment by llvasconcellos** [comment]
@fossfreedom I'm trying to run the **Rhythmbox delete current song Plugin**
http://sourceforge.net/projects/rhythmboxdelete/
Searching for the frase "The 'python' plugin loader has not been enabled" I ended up here.
Maybe you might point me to the right direction on solving this problem.
I really appreciate it.

**Comment by fossfreedom** [comment]
looking at the src plugin file it is correctly defined for python3 and thus will run correctly in your version of rhythmbox
- http://sourceforge.net/p/rhythmboxdelete/code/HEAD/tree/trunk/RhythmboxDeleteFile/src/

You'll need to contact the maintainer of the project why they have not made this version in trunk available as a download tar file.

My suggestion is that you download the trunk version and install that.

svn checkout svn://svn.code.sf.net/p/rhythmboxdelete/code/trunk rhythmboxdelete-code

**Comment by llvasconcellos** [comment]
@fossfreedom The plugin gets loaded now but its not working. I'll learn how to make my own plugins.
Thank you very much!
