### ISSUE TITLE
Can't enable while running...

### ISSUE THREAD

**Issue by samindaperamuna** [fossfreedom/rhythmbox_hide#4]
Rhythmbox won't hide when minimized..

**Comment by fossfreedom** [comment]
Hi,

  thanks for raising the issue.

I'm running ubuntu 14.04 with Unity desktop and Rhythmbox 3.2.1 -  the plugin works fine.

What combination are you running?

Start rhythmbox via a terminal.

click the minimise button.  Is there any output in the terminal as a result of clicking minimise?

**Comment by samindaperamuna** [comment]
![rberr](https://cloud.githubusercontent.com/assets/16777956/12531751/c42c6514-c228-11e5-9d71-b138356b49fa.png)

**Comment by fossfreedom** [comment]
Ok ... Having reread your issue you are expecting rhythmbox to hide when minimising the main window?

If you are using ubuntu just hit the x of the window.  Rhythmbox will hide when it's playing a song.

If you are not using ubuntu there is another plugin called hide-on-close.

This plugin hides/minimises on startup

**Comment by samindaperamuna** [comment]
Hi thanks for the reply. I am using Debian Jessie. I cant get anything to work on Rhythmbox 3.0.
