### ISSUE TITLE
Feature: hide on close

### ISSUE THREAD

**Issue by lo-zed** [fossfreedom/rhythmbox_hide#5]
Hi, first thanks for your plugin.
Would anyone else find it useful to hide the window again when pressing 'x' ?
I couldn't find any plugin doing that. There's [this one](https://github.com/cnervi/rhythmbox-hide-on-close) that doesn't work, I guess it was for rhythmbox2.

**Comment by fossfreedom** [comment]
This? https://github.com/user12043/rhythmbox-hide-on-close

**Comment by lo-zed** [comment]
ah right sorry.. I hadn't noticed the small python3 change in the forks.
Thank you very much
